### ISSUE TITLE
Unable to install opa-wasm

### ISSUE THREAD

**Issue by cch0** [a2d24/python-opa-wasm#7]
**Description**:
Unable to install opa-wasm following the install instruction. Installed without the `cranelift` or `llvm` was fine, however.

**Environment**: MacOS M1

**Steps took**
```
[~]$ pip install opa-wasm[cranelift]
zsh: no matches found: opa-wasm[cranelift]
[~]$ pip install opa-wasm[llvm]
zsh: no matches found: opa-wasm[llvm]
[~]$ pip install opa-wasm
Collecting opa-wasm
  Using cached opa_wasm-0.3.2-py3-none-any.whl (5.1 kB)
Collecting wasmer<2.0.0,>=1.0.0
  Using cached wasmer-1.1.0-py3-none-any.whl (1.6 kB)
Installing collected packages: wasmer, opa-wasm
Successfully installed opa-wasm-0.3.2 wasmer-1.1.0
```

**Versions**

```
[~]$ pip --version
pip 23.0.1 from /opt/homebrew/lib/python3.10/site-packages/pip (python 3.10)
```

**Question**
- Did I use the incorrect command ?

**Comment by imtiazmangerah** [comment]
This appears to be an issue with zsh and the square bracket syntax.

Try using `pip install "opa-wasm[cranelift]"` (with quotation marks)? If that works then the README.md should be updated to reflect this, since from my tests it appears as if both bash and zsh are fine with quotation marks.

**Comment by cch0** [comment]
> This appears to be an issue with zsh and the square bracket syntax.
> 
> Try using `pip install "opa-wasm[cranelift]"` (with quotation marks)? If that works then the README.md should be updated to reflect this, since from my tests it appears as if both bash and zsh are fine with quotation marks.

That was it, thank you. I am creating a PR to update the instruction. 

https://github.com/a2d24/python-opa-wasm/pull/8
